/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[movie_type]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[type] [varchar] (50) NOT NULL
)
GO
ALTER TABLE [dbo].[movie_type] ADD CONSTRAINT [PK_movie_type_id] PRIMARY KEY CLUSTERED ([id])
GO
