/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[movies]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[title] [varchar] (200) NOT NULL,
[description] [varchar] (2000) NOT NULL,
[movie_type_id] [int] NOT NULL,
[duration] [int] NOT NULL,
[release_date] [datetime] NOT NULL,
[added_date] [datetime] NOT NULL,
[owned] [bit] NOT NULL CONSTRAINT [DF_movies_owned] DEFAULT ((0))
)
GO
ALTER TABLE [dbo].[movies] ADD CONSTRAINT [PK_movies_id] PRIMARY KEY CLUSTERED ([id])
GO
CREATE NONCLUSTERED INDEX [IX_movies_release_date] ON [dbo].[movies] ([release_date])
GO
ALTER TABLE [dbo].[movies] ADD CONSTRAINT [FK_movies_movie_type_id] FOREIGN KEY ([movie_type_id]) REFERENCES [dbo].[movie_type] ([id])
GO
