/*
    This script was generated by SQL Change Automation to help provide object-level history. This script should never be edited manually.
    For more information see: https://www.red-gate.com/sca/dev/offline-schema-model
*/

CREATE TABLE [dbo].[series_episode]
(
[id] [int] NOT NULL IDENTITY(1, 1),
[series_id] [int] NOT NULL,
[episode_number] [int] NOT NULL,
[title] [varchar] (200) NOT NULL,
[description] [varchar] (2000) NOT NULL,
[duration] [int] NOT NULL,
[release_date] [datetime] NOT NULL,
[added_date] [datetime] NOT NULL,
[owned] [bit] NOT NULL CONSTRAINT [DF_series_episode_owned] DEFAULT ((0))
)
GO
ALTER TABLE [dbo].[series_episode] ADD CONSTRAINT [PK_series_episode_id] PRIMARY KEY CLUSTERED ([id])
GO
CREATE NONCLUSTERED INDEX [IX_series_episode_release_date] ON [dbo].[series_episode] ([release_date])
GO
ALTER TABLE [dbo].[series_episode] ADD CONSTRAINT [IX_series_id_episode_number] UNIQUE NONCLUSTERED ([series_id], [episode_number])
GO
ALTER TABLE [dbo].[series_episode] ADD CONSTRAINT [FK_series_episode_series_id] FOREIGN KEY ([series_id]) REFERENCES [dbo].[series] ([id]) ON DELETE CASCADE
GO
